# Generated by Django 3.2 on 2022-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_profile', '0005_auto_20220523_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfFac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('dob', models.DateField(default='')),
                ('phn', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('qualif', models.CharField(default='', max_length=500)),
                ('tech_skl', models.CharField(default='', max_length=200)),
                ('exp', models.CharField(default='', max_length=1000)),
                ('subj', models.CharField(default='', max_length=200)),
                ('achv', models.CharField(default='', max_length=300)),
                ('res_area', models.CharField(default='', max_length=500)),
                ('ref', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
