# Generated by Django 3.2 on 2022-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_profile', '0007_proffac_desig'),
    ]

    operations = [
        migrations.AddField(
            model_name='proffac',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='proffac',
            name='img',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
