# Generated by Django 3.2 on 2022-05-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_profile', '0010_alter_proffac_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffac',
            name='img',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
