# Generated by Django 3.2 on 2022-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_profile', '0011_alter_proffac_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffac',
            name='exp',
            field=models.TextField(default=''),
        ),
    ]
