# Generated by Django 3.2 on 2022-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20220428_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='face',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
