# Generated by Django 3.2 on 2022-04-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20220428_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='is_faculty',
        ),
        migrations.RemoveField(
            model_name='face',
            name='is_student',
        ),
    ]
