from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(student_profile)
admin.site.register(student_edu)
admin.site.register(student_adm)
admin.site.register(student_parent)
admin.site.register(student_stay)
admin.site.register(student_extra)

admin.site.register(basic_1_1)
admin.site.register(mid1_1_1)
admin.site.register(mid2_1_1)
admin.site.register(external_1_1)
admin.site.register(counselling_1_1)
admin.site.register(problems_1_1)
admin.site.register(cstatus_1_1)

admin.site.register(basic_1_2)
admin.site.register(mid1_1_2)
admin.site.register(mid2_1_2)
admin.site.register(external_1_2)
admin.site.register(counselling_1_2)
admin.site.register(problems_1_2)
admin.site.register(cstatus_1_2)

admin.site.register(basic_2_1)
admin.site.register(mid1_2_1)
admin.site.register(mid2_2_1)
admin.site.register(external_2_1)
admin.site.register(counselling_2_1)
admin.site.register(problems_2_1)
admin.site.register(cstatus_2_1)

admin.site.register(basic_2_2)
admin.site.register(mid1_2_2)
admin.site.register(mid2_2_2)
admin.site.register(external_2_2)
admin.site.register(counselling_2_2)
admin.site.register(problems_2_2)
admin.site.register(cstatus_2_2)


admin.site.register(basic_3_1)
admin.site.register(mid1_3_1)
admin.site.register(mid2_3_1)
admin.site.register(external_3_1)
admin.site.register(counselling_3_1)
admin.site.register(problems_3_1)
admin.site.register(cstatus_3_1)

admin.site.register(basic_3_2)
admin.site.register(mid1_3_2)
admin.site.register(mid2_3_2)
admin.site.register(external_3_2)
admin.site.register(counselling_3_2)
admin.site.register(problems_3_2)
admin.site.register(cstatus_3_2)

admin.site.register(basic_4_1)
admin.site.register(mid1_4_1)
admin.site.register(mid2_4_1)
admin.site.register(external_4_1)
admin.site.register(counselling_4_1)
admin.site.register(problems_4_1)
admin.site.register(cstatus_4_1)

admin.site.register(basic_4_2)
admin.site.register(mid1_4_2)
admin.site.register(mid2_4_2)
admin.site.register(external_4_2)
admin.site.register(counselling_4_2)
admin.site.register(problems_4_2)
admin.site.register(cstatus_4_2)