# Generated by Django 3.2 on 2022-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('name', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('qualif', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
