# Generated by Django 3.1.4 on 2022-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220430_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='acheivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('name', models.CharField(default='', max_length=200)),
                ('achieve', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
