# Generated by Django 3.2 on 2022-05-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220523_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac',
            name='resume',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
