# Generated by Django 3.2 on 2022-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventMode', models.CharField(blank=True, max_length=40)),
                ('EventType', models.CharField(blank=True, max_length=100)),
                ('UploadLink', models.URLField(max_length=500, unique=True)),
                ('EventDate', models.DateField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=80)),
                ('Month', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
