# Generated by Django 3.2 on 2022-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosengers', '0002_auto_20220430_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('activity', models.CharField(default='', max_length=150)),
                ('res_persn', models.CharField(default='', max_length=150)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('relevance', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
