# Generated by Django 3.1.4 on 2022-05-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosengers', '0003_auto_20220515_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
