# Generated by Django 3.2 on 2022-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosengers', '0005_auto_20220523_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='img2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='img3',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
