# Generated by Django 3.2 on 2022-05-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosengers', '0006_auto_20220523_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(default='')),
                ('link', models.URLField(default='')),
                ('desc', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
