# Generated by Django 3.1.4 on 2022-07-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20220704_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='sem',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='year',
            field=models.CharField(default=2, max_length=1),
        ),
    ]
