# Generated by Django 3.1.4 on 2022-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20220707_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='mid2_1_1',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_1',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_1_2',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_1',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_2_2',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_1',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_3_2',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_1',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mid2_4_2',
            name='s9_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
